// Generated by CoffeeScript 1.4.0
var MongoStore, app, assets, cards, express, mongoose, port, sessions, stylus, users;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

mongoose = require('mongoose');

MongoStore = require('connect-mongo')(express);

require('express-resource');

app = express();

app.configure('dev', function() {
  app.set('db-host', "localhost");
  return app.set('db-name', "dummy");
});

app.configure('test', function() {
  app.set('db-host', "localhost");
  return app.set('db-name', "cardbank-test");
});

app.configure('prod', function() {
  app.set('db-host', "localhost");
  return app.set('db-name', "cardbank-prod");
});

app.configure(function() {
  var store;
  app.use(assets());
  app.use(express["static"](process.cwd() + '/public'));
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(express.cookieParser());
  store = new MongoStore({
    db: app.set('db-name'),
    stringify: false
  });
  app.use(express.session({
    store: store,
    secret: 'topsecret'
  }));
  return app.use(express.logger());
});

app.db = mongoose.connect(app.set('db-host'), app.set('db-name'));

users = app.resource('users', require('./controllers/user'));

cards = app.resource('cards', require('./controllers/card'));

users.add(cards);

sessions = app.resource('sessions', require('./controllers/session'));

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
