// Generated by CoffeeScript 1.6.3
var Card, CardController;

Card = require('../models/card');

CardController = {
  index: function(req, res) {
    return Card.find({
      userId: req.user.id
    }, null, {
      sort: ['lastName', 'descending']
    }, function(err, data) {
      if (err) {
        res.send({
          err: err
        });
      }
      return res.send(data);
    });
  },
  create: function(req, res) {
    var body, card;
    if (!req.user) {
      res.send('not authenticated');
    }
    body = req.body;
    body.userId = req.user.id;
    card = new Card(body);
    return card.save(function(err, val) {
      if (err) {
        res.send({
          err: err
        });
      }
      return res.send(val);
    });
  },
  show: function(req, res) {
    return res.send(req.card);
  },
  load: function(req, id, fn) {
    var res;
    res = req.res;
    return Card.findOne({
      _id: id,
      userId: req.user.id
    }, function(err, data) {
      if (err) {
        return res.send({
          error: err
        });
      } else {
        return fn(null, data);
      }
    });
  }
};

module.exports = CardController;
