// Generated by CoffeeScript 1.6.3
var Card, ContactController, User;

User = require('../models/user');

Card = require('../models/card');

ContactController = {
  index: function(req, res) {
    if (!req.user) {
      res.send('not authenticated');
    }
    return Card.find({
      _id: {
        $in: req.user.contacts
      }
    }, function(err, data) {
      if (err) {
        res.send({
          err: err
        });
      }
      return res.send({
        status: 'success',
        contacts: data
      });
    });
  },
  create: function(req, res) {
    if (!req.user) {
      res.send('not authenticated');
    }
    return User.update({
      _id: req.user.id
    }, {
      $addToSet: {
        contacts: req.body.cardId
      }
    }, function(err, val) {
      if (err) {
        res.send({
          err: err
        });
      }
      return res.send('success');
    });
  }
};

module.exports = ContactController;
