// Generated by CoffeeScript 1.6.3
var SessionController, User;

User = require('../models/user');

SessionController = {
  create: function(req, res) {
    var body;
    body = req.body;
    return User.findOne({
      email: body.email
    }, function(err, user) {
      if (err) {
        res.send({
          err: err
        });
      }
      if (user && user.authenticate(body.password)) {
        req.session.userId = user.id;
        return res.send({
          userId: user.id
        });
      } else {
        return res.send({
          err: "failed to authenticate " + body.email
        });
      }
    });
  }
};

module.exports = SessionController;
