// Generated by CoffeeScript 1.4.0
var SessionController, User;

User = require('../models/user');

SessionController = {
  create: function(req, res) {
    var body;
    body = req.body;
    return User.findOne({
      email: body.email
    }, function(err, user) {
      if (err) {
        res.send({
          err: err
        });
      }
      if (user && user.authenticate(body.password)) {
        req.session.userId = user.id;
        return res.send("authenticated " + body.email);
      } else {
        return res.send("failed to authenticate " + body.email);
      }
    });
  }
};

module.exports = SessionController;
