// Generated by CoffeeScript 1.6.3
var User, UserController;

User = require('../models/user');

UserController = {
  index: function(req, res) {
    if (req.session.count) {
      console.log(' fount');
      req.session.count = req.session.count + 1;
    } else {
      console.log('not fount');
      req.session.count = 1;
    }
    console.log(req.session);
    return res.send("index users");
  },
  create: function(req, res) {
    var body, user;
    console.log("create user");
    console.log(req.body);
    body = req.body;
    user = new User({
      email: body.email,
      password: body.password,
      myCards: [],
      cards: []
    });
    return user.save(function(err, val) {
      if (err) {
        console.log('error: ', err);
        res.send(err);
      }
      return res.send(val);
    });
  },
  show: function(req, res) {
    console.log("show user " + req.params.user);
    return res.send(req.user);
  },
  load: function(req, id, fn) {
    var res;
    res = req.res;
    console.log('req.session', req.session);
    if (req.session.userId && req.session.userId === id) {
      return User.findOne({
        _id: req.session.userId
      }, function(err, data) {
        if (err) {
          return res.send({
            error: err
          });
        } else {
          return fn(null, data);
        }
      });
    } else {
      return res.send("not authorized");
    }
  }
};

module.exports = UserController;
